name: Deploy frontend to GitHub Pages

on:
  push:
    branches: [ main ]  # or your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: apps/web-os/package-lock.json

      - name: Install deps
        run: |
          cd apps/web-os
          npm ci

      - name: Build with base path for project pages
        env:
          # IMPORTANT: base path becomes /<repo>/
          VITE_BASE_PATH: "/${{ github.event.repository.name }}/"
          VITE_SERVER_ENABLED: "false"
        run: |
          cd apps/web-os
          npm run build

      - name: SPA fallback (404.html)
        run: |
          cp apps/web-os/dist/index.html apps/web-os/dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web-os/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
